version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - backend

  server:
    image: stensh1/flood-control
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - redis
    links:
      - redis

networks:
  backend: